/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Killer */

#ifndef _Included_Killer
#define _Included_Killer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Killer
 * Method:    killMeNow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Killer_killMeNow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
